use docx_rs::*;
use serde::{Deserialize, Serialize};
use std::fs::File;
use chrono::Local;
use tauri::{command, AppHandle, State};
use std::sync::Mutex;
use crate::l1_rag::{GemmaEngine};
use crate::l6_audit::get_db_connection;
use crate::state;

#[derive(Debug, Serialize, Deserialize)]
pub struct EsrsReportRow {
    pub id: String,
    pub name: String,
    pub status: String,
    pub missing_items: String,
    pub reference: String,
}

#[command]
pub async fn generate_report(
    app_handle: AppHandle,
    engine_state: State<'_, Mutex<Option<GemmaEngine>>>,
    client_id: i32,
    company_name: String,
    language: String,
) -> Result<String, String> {
    // 1. Fetch AI Analysis Data
    let analysis = crate::l1_rag::analyze_imported_data(app_handle.clone(), client_id, engine_state).await?;
    
    // 2. Fetch Real SSOT Data from DB
    let conn = get_db_connection(&app_handle).map_err(|e| e.to_string())?;
    
    let industry: String = conn.query_row(
        "SELECT industry FROM clients WHERE id = ?1",
        [client_id],
        |row| row.get(0)
    ).unwrap_or_else(|_| "Unknown".to_string());

    let scope1_gas = state::get_esg_total(&conn, client_id, "scope1_gas");
    let scope1_fuel = state::get_esg_total(&conn, client_id, "scope1_fuel");
    let scope1_ref = state::get_esg_total(&conn, client_id, "scope1_refrigerant");
    let scope2 = state::get_esg_total(&conn, client_id, "scope2_electricity");
    let scope3 = state::get_esg_total(&conn, client_id, "scope3_supplier");
    
    let s1_gas_co2 = (scope1_gas * 2.04) / 1000.0;
    let s1_fuel_co2 = (scope1_fuel * 2.68) / 1000.0;
    let s1_ref_co2 = (scope1_ref * 2088.0) / 1000.0;
    let s2_co2 = (scope2 * 0.276) / 1000.0;
    
    let scope1_total = s1_gas_co2 + s1_fuel_co2 + s1_ref_co2;
    let total_carbon = scope1_total + s2_co2 + scope3;
    
    let workforce = state::get_esg_total(&conn, client_id, "workforce");
    let training_cost = state::get_esg_total(&conn, client_id, "training_cost");

    // 3. Calculate Overall ESG Score
    let total_checks = 4.0; 
    let compliant_count = analysis.compliant.len() as f64;
    let esg_score = ((compliant_count / total_checks) * 100.0).min(100.0) as i32;

    let date = Local::now().format("%Y-%m-%d").to_string();
    let is_de = language.to_lowercase() == "de";

    // 4. Prepare Document
    let mut docx = Docx::new();

    // --- COVER PAGE ---
    docx = docx
        .add_paragraph(
            Paragraph::new()
                .add_run(Run::new().add_text(company_name.clone()).size(64).bold())
                .align(AlignmentType::Center)
        )
        .add_paragraph(
            Paragraph::new()
                .add_run(Run::new().add_text(format!("Industry: {}", industry)).size(28))
                .align(AlignmentType::Center)
        )
        .add_paragraph(
            Paragraph::new()
                .add_run(Run::new().add_text("CSRD Sustainability Report 2024").size(36).bold())
                .align(AlignmentType::Center)
        )
        .add_paragraph(
            Paragraph::new()
                .add_run(Run::new().add_text("Generated by Targoo ESG Advisor").size(24).italic())
                .align(AlignmentType::Center)
        )
        .add_paragraph(
            Paragraph::new()
                .add_run(Run::new().add_text(format!("Date: {}", date)).size(20))
                .align(AlignmentType::Center)
        )
        .add_paragraph(Paragraph::new().add_run(Run::new().add_break(BreakType::Page)));

    // --- SECTION 1: EXECUTIVE SUMMARY ---
    let exec_title = if is_de { "MANAGEMENT-ZUSAMMENFASSUNG" } else { "SECTION 1: EXECUTIVE SUMMARY" };
    docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_text(exec_title).size(32).bold()));
    
    docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_text(format!("Overall ESG Score: {}/100", esg_score)).size(24).bold()));
    
    let summary_text = format!(
        "This report provides a comprehensive overview of the sustainability performance for {}. As of {}, the total recorded carbon footprint is {:.2} tCO2e. The organization shows a compliance level of {}% across the initial ESRS assessment criteria.",
        company_name, date, total_carbon, esg_score
    );
    docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_text(summary_text).size(22)));

    docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_text("AI Advisory Insights:").size(24).bold()));
    docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_text(analysis.proactive_message.clone()).size(20)));

    // --- SECTION 2: ENVIRONMENTAL (ESRS E1) ---
    docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_break(BreakType::Page)));
    docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_text("SECTION 2: ENVIRONMENTAL (ESRS E1)").size(32).bold()));
    docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_text("Climate change mitigation and energy consumption breakdown.").size(22)));

    let mut env_table = Table::new(vec![]);
    env_table = env_table.add_row(TableRow::new(vec![
        TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text("Metric").bold())),
        TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text("Value (tCO2e)").bold())),
    ]));
    env_table = env_table.add_row(TableRow::new(vec![
        TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text("Scope 1: Direct Emissions"))),
        TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text(format!("{:.2}", scope1_total)))),
    ]));
    env_table = env_table.add_row(TableRow::new(vec![
        TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text("Scope 2: Energy Indirect Emissions"))),
        TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text(format!("{:.2}", s2_co2)))),
    ]));
    env_table = env_table.add_row(TableRow::new(vec![
        TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text("Total Carbon Footprint").bold())),
        TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text(format!("{:.2}", total_carbon)).bold())),
    ]));
    docx = docx.add_table(env_table);

    // --- SECTION 3: SOCIAL (ESRS S1) ---
    docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_text("\nSECTION 3: SOCIAL (ESRS S1)").size(32).bold()));
    docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_text(format!("Current Workforce: {:.0} Employees", workforce)).size(22)));
    docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_text(format!("Training & Development Investment: {:.2} EUR", training_cost)).size(22)));

    // --- SECTION 4: COMPLIANCE TABLE ---
    docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_break(BreakType::Page)));
    docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_text("SECTION 4: ESRS COMPLIANCE STATUS").size(32).bold()));

    let mut comp_table = Table::new(vec![]);
    comp_table = comp_table.add_row(TableRow::new(vec![
        TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text("ESRS Standard").bold())),
        TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text("Status").bold())),
        TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text("Reference").bold())),
    ]));

    let standards = vec![
        ("ESRS E1", "Climate Change", total_carbon > 0.0, "E1.44"),
        ("ESRS E3", "Water & Marine", state::get_esg_total(&conn, client_id, "water") > 0.0, "E3.12"),
        ("ESRS E5", "Resource Use", state::get_esg_total(&conn, client_id, "waste") > 0.0, "E5.24"),
        ("ESRS S1", "Own Workforce", workforce > 0.0, "S1.12"),
        ("ESRS G1", "Business Conduct", false, "G1.01"),
    ];

    for (id, name, is_complete, ref_code) in standards {
        let status = if is_complete { "✅ Complete" } else { "❌ Missing" };
        comp_table = comp_table.add_row(TableRow::new(vec![
            TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text(format!("{}: {}", id, name)))),
            TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text(status))),
            TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text(ref_code))),
        ]));
    }
    docx = docx.add_table(comp_table);

    // 5. Save Document
    let desktop_dir = dirs::desktop_dir().ok_or("Could not find Desktop directory")?;
    let file_name = format!("{}_ESG_Report_{}.docx", company_name.replace(" ", "_"), date);
    let path = desktop_dir.join(&file_name);

    let file = File::create(&path).map_err(|e| format!("Failed to create file: {}", e))?;
    docx.build().pack(file).map_err(|e| format!("Failed to build docx: {}", e))?;

    Ok(path.to_string_lossy().to_string())
}
