use docx_rs::*;
use serde::{Deserialize, Serialize};
use std::fs::File;
use chrono::Local;
use tauri::{command, AppHandle, State};
use std::sync::Mutex;
use crate::l1_rag::{GemmaEngine};
use crate::l6_audit::get_db_connection;

#[derive(Debug, Serialize, Deserialize)]
pub struct EsrsReportRow {
    pub id: String,
    pub name: String,
    pub status: String,
    pub missing_items: String,
    pub reference: String,
}

#[command]
pub async fn generate_report(
    app_handle: AppHandle,
    engine_state: State<'_, Mutex<Option<GemmaEngine>>>,
    company_name: String,
    language: String,
) -> Result<String, String> {
    // 1. Fetch AI Analysis Data
    let analysis = crate::l1_rag::analyze_imported_data(app_handle.clone(), engine_state).await?;
    
    // 2. Fetch Imported Data from DB for Summary info
    let conn = get_db_connection(&app_handle).map_err(|e| e.to_string())?;
    let imported_count: i64 = conn.query_row("SELECT COUNT(*) FROM imported_data", [], |row| row.get(0)).unwrap_or(0);

    // 3. Calculate Overall ESG Score (Mock logic based on E1 compliance)
    let total_checks = 4.0; 
    let compliant_count = analysis.compliant.len() as f64;
    let esg_score = ((compliant_count / total_checks) * 100.0).min(100.0) as i32;

    let date = Local::now().format("%Y-%m-%d").to_string();
    let is_de = language.to_lowercase() == "de";

    // 4. Prepare Document
    let mut docx = Docx::new();

    // --- COVER PAGE ---
    docx = docx
        .add_paragraph(
            Paragraph::new()
                .add_run(Run::new().add_text("").add_break(BreakType::Page)) // Dummy to ensure start
        )
        .add_paragraph(
            Paragraph::new()
                .add_run(Run::new().add_text(company_name.clone()).size(64).bold())
                .align(AlignmentType::Center)
        )
        .add_paragraph(
            Paragraph::new()
                .add_run(Run::new().add_text("CSRD Sustainability Report 2024").size(36))
                .align(AlignmentType::Center)
        )
        .add_paragraph(
            Paragraph::new()
                .add_run(Run::new().add_text("Generated by Targoo ESG Advisor").size(24).italic())
                .align(AlignmentType::Center)
        )
        .add_paragraph(
            Paragraph::new()
                .add_run(Run::new().add_text(format!("Date: {}", date)).size(20))
                .align(AlignmentType::Center)
        )
        .add_paragraph(Paragraph::new().add_run(Run::new().add_break(BreakType::Page)));

    // --- EXECUTIVE SUMMARY ---
    let exec_title = if is_de { "MANAGEMENT-ZUSAMMENFASSUNG" } else { "EXECUTIVE SUMMARY" };
    docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_text(exec_title).size(28).bold()));
    
    docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_text(format!("Overall ESG Score: {}/100", esg_score)).size(24).bold()));
    docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_text(format!("Data Points Analyzed: {}", imported_count)).size(16)));
    
    let findings_title = if is_de { "Top 3 Feststellungen" } else { "Top 3 Findings" };
    docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_text(findings_title).size(20).bold()));
    if analysis.compliant.is_empty() {
        docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_text("- No compliance items found yet.")));
    } else {
        for finding in analysis.compliant.iter().take(3) {
            docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_text(format!("• {}", finding))));
        }
    }

    let gaps_title = if is_de { "Kritische Lücken" } else { "Critical Gaps" };
    docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_text(gaps_title).size(20).bold()));
    if analysis.missing.is_empty() && analysis.warnings.is_empty() {
        docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_text("- No critical gaps identified.")));
    } else {
        for gap in analysis.missing.iter().take(2) {
            docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_text(format!("• {}", gap))));
        }
        for warning in analysis.warnings.iter().take(1) {
            docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_text(format!("• Warning: {}", warning))));
        }
    }

    docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_text("AI Advisory Message:").size(18).bold()));
    docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_text(analysis.proactive_message.clone()).size(16)));

    // --- GAP ANALYSIS TABLE ---
    docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_break(BreakType::Page)));
    docx = docx.add_paragraph(Paragraph::new().add_run(Run::new().add_text("GAP ANALYSIS TABLE FOR ESRS STANDARDS").size(24).bold()));

    let mut table = Table::new(vec![]);
    // Header
    let header_row = TableRow::new(vec![
        TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text("ESRS Standard").bold())),
        TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text("Status").bold())),
        TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text("Missing items").bold())),
        TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text("Paragraph reference").bold())),
    ]);
    table = table.add_row(header_row);

    // List of ESRS standards per requirement
    let standards = vec![
        ("ESRS E1", "Climate change", "E1.44, E1.46", "Scope 1, 2, 3 Emissions, Energy Consumption"),
        ("ESRS E2", "Pollution", "E2.22", "Air pollutants, Water pollutants"),
        ("ESRS E3", "Water and marine resources", "E3.12", "Water consumption, Water recycling"),
        ("ESRS E4", "Biodiversity and ecosystems", "E4.18", "Impact on protected areas"),
        ("ESRS E5", "Resource use and circular economy", "E5.24", "Waste generated, Material use"),
        ("ESRS S1", "Own workforce", "S1.12", "Employee numbers, Gender pay gap"),
        ("ESRS S2", "Workers in the value chain", "S2.08", "Human rights risks in supply chain"),
        ("ESRS S3", "Affected communities", "S3.05", "Community impact assessments"),
        ("ESRS S4", "Consumers and end-users", "S4.04", "Privacy, Health and safety"),
    ];

    for (id, name, ref_code, items) in standards {
        let status = if id == "ESRS E1" {
            if esg_score > 75 { "✅" } else if esg_score > 30 { "⚠️" } else { "❌" }
        } else {
            "❌" 
        };
        
        let missing = if status == "✅" { if is_de { "Keine" } else { "None" } } else { items };

        let row = TableRow::new(vec![
            TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text(format!("{}: {}", id, name)))),
            TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text(status)).align(AlignmentType::Center)),
            TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text(missing))),
            TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text(ref_code))),
        ]);
        table = table.add_row(row);
    }
    docx = docx.add_table(table);

    // 5. Save Document
    let desktop_dir = dirs::desktop_dir().ok_or("Could not find Desktop directory")?;
    let file_name = format!("{}_ESG_Report_{}.docx", company_name.replace(" ", "_"), date);
    let path = desktop_dir.join(&file_name);

    let file = File::create(&path).map_err(|e| format!("Failed to create file: {}", e))?;
    docx.build().pack(file).map_err(|e| format!("Failed to build docx: {}", e))?;

    Ok(path.to_string_lossy().to_string())
}
